### ISSUE TITLE
Placing Yuzu Generator crashes game

### ISSUE THREAD

**Issue by Devalut** [defeatedcrow/EconomicalMilkTea#4]
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 9/9/16 11:30 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
    at ic2.api.energy.prefab.BasicSource.<init>(BasicSource.java:103)
    at defeatedcrow.addonforamt.economy.plugin.energy.EUSourceChannelEMT.<init>(EUSourceChannelEMT.java:12)
    at defeatedcrow.addonforamt.economy.plugin.energy.EUSourceManagerEMT.getChannel(EUSourceManagerEMT.java:17)
    at defeatedcrow.addonforamt.economy.common.block.GeneratorBase.<init>(GeneratorBase.java:50)
    at defeatedcrow.addonforamt.economy.common.block.TileENTank.<init>(TileENTank.java:26)
    at defeatedcrow.addonforamt.economy.common.block.BlockENTank.func_149915_a(BlockENTank.java:195)
    at net.minecraft.block.Block.createTileEntity(Block.java:1446)
    at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:850)
    at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:660)
    at net.minecraft.world.World.func_147465_d(World.java:451)
    at net.minecraft.item.ItemBlock.placeBlockAt(ItemBlock.java:206)
    at net.minecraft.item.ItemBlock.func_77648_a(ItemBlock.java:103)
    at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:129)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:360)
    at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1447)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1953)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by defeatedcrow** [comment]
Since your crash report is incomplete, the cause can not be specific.
It is probably going by other mods that including the incomplete IC2API.

The simplest solution is to introduce the IC2. (It includes the always full IC2API.)
Alternatively, you can also be solved by introducing the IC2API in any.

**Comment by Devalut** [comment]
Thank you so much this fixed it completely!
However attaching wires and rf transferring devices result in no energy being moved, currently only Thermal Expansion Cells can accept energy...

Also is the energy produced is very minuscule

**Comment by defeatedcrow** [comment]
RF Motor device requires the RS signal for running.
![motor](https://dl-web.dropbox.com/s/hhmlmdtb8yrce6h/YuzuMotor.png)

> Also is the energy produced is very minuscule

It is a matter of course. :D
The main elements of this add-on is the energy purchase by money (MP money of MCEconomy2). Element of homemade energy is included only to a minimum.
